version: 2.10.2
services:
   angular-service:
     container_name: angular-container
     build:
             context: .
             dockerfile: Dockerfile
     ports:
             - 4200:4200
     volumes:
             - .:/app
             - /app/node_modules
     command: bash -c "npm start"

